config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'votes#index'

  get 'users/:id' => 'users#show', as: 'user'
  post 'votes'    => 'votes#create'
  get 'results'   => 'elections#results'
  get 'dashboard' => 'elections#dashboard'
  get 'election' => 'elections#election'
  
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/election.rb
class Election < ActiveRecord::Base
  has_many :votes

  validates_presence_of  :month, :year
  validates_uniqueness_of :month, scope: :year

  def winners
    max_votes = self.votes.group(:selection_id).count.max[1]
    winners   = self.votes.group(:selection_id).count.select{|id, vote_count| vote_count == max_votes}
    winners.map { |id, vote_count| {user: User.find(id), vote_count: vote_count} }
  end

  def tie?
    winners.size > 1
  end

  def self.last_election
    date = Date.today - 1.month
    where(month: date.month, year: date.year).take
  end

  def current_leaders
    winners
  end

  def self.current_leaders
    where(month: Date.today.month, year: Date.today.year).take.try(:current_leaders)
  end

  def self.last_month
    date = Date.today - 1.month
    where(month: date.month, year: date.year).take
  end

  def self.last_winners
    last_election.try(:winners) || []
  end

  def self.winners_of(month, year)
    where(month: month, year: year).take.try(:winners) || []
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes, class_name: "Vote", foreign_key: "voter_id"
	has_many :selections, class_name: "Vote", foreign_key: "selection_id"

	validates_presence_of :first_name, :last_name

  # blocks possibility of two people named "Flannery O'Connor" from existing
  # remove line to allow duplicate first/last name combinations
  validates_uniqueness_of :first_name, scope: :last_name

	def full_name
		self.first_name.downcase.capitalize + " " + self.last_name.downcase.capitalize
	end

  def can_vote?
    vote = Vote.where(voter_id: self.id).last
    if vote && vote.created_at.month == Time.now.month && vote.created_at.year == Time.now.year
      return false
    else
      return true
    end
    # once we're using Postgres:
    # Entry.where('voter_id = ? AND extract(month from created_at) = ? AND extract(year from created_at) = ?', self.id, Time.now.month, Time.now.year).blank?
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :election
	belongs_to :voter, class_name: "User"
  belongs_to :selection, class_name: "User"

  validates_presence_of :selection, :voter

  scope :for_user, -> (user) { where(selection_id: user.id) }
  scope :by_user,  -> (user) { where(voter_id: user.id) }

  def comment
    read_attribute(:comment) || ''
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  private
    def admin_user?
      current_user.admin?
    end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user?, only: [:dashboard]

  def results
    # [{user: <User:248264>, votes: 3, comments: []}]
    @election = Election.last_month
    @winners  = @election.winners
    @winners.map! do |winner|
      comments = @election.votes.where(selection_id: winner[:user].id).pluck(:comment)
      { user: winner[:user], vote_count: winner[:vote_count], comments: comments }
    end
    # [{user: <Class: User>, vote_count: 3, comments: ["comment"]}]
  end

  def dashboard
    @elections = Election.joins("LEFT OUTER JOIN votes ON votes.election_id = elections.id").where.not(votes: {election_id: nil}).uniq.pluck(:month, :year, :id)
    @elections_collection = @elections.map { |e| ["#{Date::MONTHNAMES[e[0]]} - #{e[1]}", e[2]] }
  end

  # returns JSON about single election for dashboard
  def election
    election = Election.find(params[:election_id])
    votes = election.votes.joins(:voter).joins(:selection).order(:selection_id).
      to_json(methods: :comment, include: {
        voter: {methods: :full_name},
        selection: {methods: :full_name}
      })
    render json: { msg: "hello dar", election: election, votes: votes }
    # votes => [{"id"=>15, "voter_id"=>4, "selection_id"=>3, "comment"=>"who else could even deal with it?", "created_at"=>"2015-02-21T19:23:19.971Z", "updated_at"=>"2015-03-21T18:23:19.972Z", "election_id"=>nil, "voter"=>{"first_name"=>"caleb", "last_name"=>"sanchez"}, "selection"=>{"first_name"=>"Jacob", "last_name"=>"Barrieault"}}]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id)
  end

	def create
    if !current_user.can_vote?
      flash[:error] = "You have already voted this month."
    else
      election = Election.where(month: Date.today.month, year: Date.today.year).first_or_create
  		vote = Vote.new(election_id: election.id, voter_id: current_user.id, selection_id: params[:selection_id], comment: params[:comment])
      if election.persisted? && vote.save
    		flash[:alert] = "You did it!"
      else
        flash[:error] = "Something went horribly wrong. We couldn't count your vote!"
      end
    end
		redirect_to root_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/elections/dashboard.html.erb
<h1>Dashboard</h1>

<!-- select election months/years, submit via ajax -->
<div>
  <%= form_tag("/election", id: 'election-form', remote: true, method: "get") do %>
    <%= select_tag(:election_id, options_for_select(@elections_collection, :id)) %>

    <%= submit_tag "Select" %>
  <% end %>
</div>
<!-- display all votes for the election and comments -->
<!-- order by selected vote ie all votes for caleb, then all votes for jacob -->

<div id="election-results">
  <ul><li>Voter</li><li>Selection</li><li>Comment</li></ul>
  <div class="votes"></div>
  <!-- rows added via js -->
</div>

app/views/elections/results.html.erb
<h1><%= (Date.today - 1.month).strftime("%B") %> Results</h1>

<div class="winners">

  <% @winners.each do |winner| %>
    <div class="winner">
      <h3><%= winner[:user].full_name.titleize %></h3>
        <%#= winner[:vote_count] %>
      <ul>
        <% winner[:comments].each do |comment| %>
          <% if comment.present? %>
            <li><%= comment %></li>
          <% end %>
        <% end %>

      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Perks</title>
  <script src="//use.typekit.net/kop2ppg.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| -%>
   <%= content_tag :div, msg, class: name %>
<% end -%>

 <!-- you can put this in a header navbar thingy -->
<div class="navbar">
  <% if user_signed_in? %>
    <!-- <span class="current-user"><%= current_user.first_name %></span> -->
    <%= link_to_if current_user.admin?, 'Dashboard', dashboard_path, :class => 'navbar-link' %> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>

app/views/votes/index.html.erb
<section class="form">
	<article>
		<img class="logo" src="/assets/logo.svg" alt="Bonfire Red Logo">
		<h1>How we make things is just as important as what we make.</h1>
		<p>Bonfire Red was built around the idea that great work should be challenging, and the challenge should be fun. We strive to maintain an open culture where everyone is a contributor and feels comfortable sharing ideas and opinions. It’s really the people that make Bonfire Red the kind of company it is. This is one way we can highlight individual associates for adding fuel to our flame.</p>

		<% if current_user.can_vote? %>
			<%= form_tag(votes_path, method: "post") do %>
			  <%= label_tag(:selection_id, "Choose an associate.") %>
			  <%= select_tag :selection_id, options_from_collection_for_select(@users, 'id', 'full_name') %>
			  <%= label_tag(:comment, "Say something awesome about her/him.") %>
			  <%= text_area_tag('comment') %>
			  <%= submit_tag("Submit Your Vote") %>
			<% end %>
		<% else %>
			<!-- put whatever you want to say to peple who have already voted right here -->
		<% end %>
	</article>
</section>

app/views/votes/results.html.erb
<h1><%= Date.today.strftime("%B") %> Results</h1>

<div class="winners">

  <% @winners.each do |winner| %>
    <div class="winner">
      <h3><%= winner[:user].full_name.titleize %></h3>
        <%#= winner[:votes] %>
      <ul>
        <% winner[:comments].each do |comment| %>
          <li><%= comment %></li>
        <% end %>

      </ul>
    </div>
  <% end %>
</div>